#!/bin/bash
#
# $1 msg file, $2 type of message
FULL_BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
BRANCH_NAME=$(echo "$FULL_BRANCH_NAME" | perl -pe 's/_/ #/, s/$/: /')
OLD_MESSAGE=$(cat "$1")
echo "$BRANCH_NAME" > "$1"
echo -n "$OLD_MESSAGE" >> "$1"
