#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook 'git'
cookbook 'readline', '~> 0.0.5'
cookbook 'ruby_build'
cookbook 'rbenv', git: 'git://github.com/chourobin/chef-rbenv.git'
cookbook 'nodejs'
